// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBPTrsDSUlF_SK1D8YQxRrNZQ6h_GJqpo',
    appId: '1:668391589242:web:93dab61a99a0e9ee5f42c3',
    messagingSenderId: '668391589242',
    projectId: 'bookmark-170cf',
    authDomain: 'bookmark-170cf.firebaseapp.com',
    storageBucket: 'bookmark-170cf.appspot.com',
    measurementId: 'G-3KYZR9BQCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhl1ZOHvtaEHyz_uQo05qO37Vmb01dYHU',
    appId: '1:668391589242:android:64bddfbdf283c04e5f42c3',
    messagingSenderId: '668391589242',
    projectId: 'bookmark-170cf',
    storageBucket: 'bookmark-170cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbKdVll_7bs2WSBpLOkvSx__AawOoq38I',
    appId: '1:668391589242:ios:8a217ebd4e5b16ad5f42c3',
    messagingSenderId: '668391589242',
    projectId: 'bookmark-170cf',
    storageBucket: 'bookmark-170cf.appspot.com',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbKdVll_7bs2WSBpLOkvSx__AawOoq38I',
    appId: '1:668391589242:ios:ce54d866b3c9e5085f42c3',
    messagingSenderId: '668391589242',
    projectId: 'bookmark-170cf',
    storageBucket: 'bookmark-170cf.appspot.com',
    iosBundleId: 'com.example.sample.RunnerTests',
  );
}
